site_name: JustinWritesCode Common Documentation
site_description: JustinWritesCode Documentation
site_url: https://justinwritescode.com
site_author: "Justin Chase"
repo_url: https://github.com/justinwritescode/dotnet-search
repo_name: justinwritescode/dotnet-search
edit_uri: "tree/main/docs"
docs_dir: docs
nav:
  - README.md
